### ISSUE TITLE
wrong number of arguments(3 for 0)

### ISSUE THREAD

**Issue by lunks** [apotonick/rspec-apotomo#5]
On a newly generated widget, I get this error.

```
  1) AlertsWidget should render :display
     Failure/Error: root << widget(:Alerts)
     ArgumentError:
       wrong number of arguments(3 for 0)
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/widget_shortcuts.rb:44:in `initialize'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/widget_shortcuts.rb:44:in `new'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/widget_shortcuts.rb:44:in `build'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/widget_shortcuts.rb:58:in `<<'
     # ./spec/widgets/alerts_widget_spec.rb:5:in `block (2 levels) in <top (required)>'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/test_case.rb:77:in `instance_exec'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/test_case.rb:77:in `block in root'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/test_case.rb:76:in `tap'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/test_case.rb:76:in `root'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/apotomo-1.2.1/lib/apotomo/test_case.rb:55:in `render_widget'
     # ./spec/widgets/alerts_widget_spec.rb:9:in `block (2 levels) in <top (required)>'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example.rb:51:in `instance_eval'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example.rb:51:in `block in run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example.rb:110:in `with_around_hooks'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example.rb:48:in `run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example_group.rb:306:in `block in run_examples'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example_group.rb:302:in `map'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example_group.rb:302:in `run_examples'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/example_group.rb:274:in `run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/command_line.rb:24:in `map'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/command_line.rb:24:in `block in run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/reporter.rb:12:in `report'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/command_line.rb:21:in `run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/runner.rb:69:in `run'
     # /Users/lunks/.rvm/gems/ruby-1.9.3-p0@tarifador/gems/rspec-core-2.7.1/lib/rspec/core/runner.rb:10:in `block in autorun'

Finished in 8.83 seconds
1 example, 1 failure
```

``` ruby
#app/widgets/alerts_widget.rb
class AlertsWidget < Apotomo::Widget

  def display
    render
  end

end
```

``` ruby
#spec/widgets/alerts_widget_spec.rb

require 'spec_helper'

describe AlertsWidget do
  has_widgets do |root|
    root << widget(:Alerts)
  end

  it "should render :display" do
    render_widget(:Alerts).should have_selector("h1")
  end
end
```

```
#Gemfile.lock
    apotomo (1.2.1)
      cells (>= 3.6.7)
      hooks (~> 0.2.0)
      onfire (~> 0.2.0)
```

**Comment by lunks** [comment]
Nevermind, my mistake.
